//! Content fingerprinting for rename and move detection.
//!
//! A fingerprint is a blake2b-128 digest over the file size (8 bytes,
//! little-endian) and the first and last 64 KiB of content. Reading at most
//! 128 KiB keeps fingerprinting fast on high-latency network mounts.
//!
//! Byte-for-byte parity with the original Python implementation
//! (hashlib.blake2b(digest_size=16)) is REQUIRED: existing stores carry
//! fingerprints written by it, and repair matches against them. The parity
//! tests below pin digests generated by that implementation.
//!
//! Deliberate tradeoff: two same-size files differing only strictly between
//! the head and tail chunks share a fingerprint. Fingerprints locate files
//! for tag relinking; they are not integrity checksums.

use blake2::digest::{Update, VariableOutput};
use blake2::Blake2bVar;
use std::io::{Read, Seek, SeekFrom};
use std::path::Path;

pub const CHUNK_SIZE: u64 = 64 * 1024;
const DIGEST_SIZE: usize = 16;

pub fn fingerprint_file(path: &Path) -> Result<String, String> {
    let mut file =
        std::fs::File::open(path).map_err(|e| format!("cannot open {}: {}", path.display(), e))?;
    let size = file
        .metadata()
        .map_err(|e| format!("cannot stat {}: {}", path.display(), e))?
        .len();

    let mut hasher = Blake2bVar::new(DIGEST_SIZE).expect("16 is a valid blake2b digest size");
    hasher.update(&size.to_le_bytes());

    let read_err = |e: std::io::Error| format!("cannot read {}: {}", path.display(), e);
    if size <= 2 * CHUNK_SIZE {
        let mut buf = Vec::with_capacity(size as usize);
        file.read_to_end(&mut buf).map_err(read_err)?;
        hasher.update(&buf);
    } else {
        let mut chunk = vec![0u8; CHUNK_SIZE as usize];
        file.read_exact(&mut chunk).map_err(read_err)?;
        hasher.update(&chunk);
        file.seek(SeekFrom::End(-(CHUNK_SIZE as i64)))
            .map_err(read_err)?;
        file.read_exact(&mut chunk).map_err(read_err)?;
        hasher.update(&chunk);
    }

    let mut digest = [0u8; DIGEST_SIZE];
    hasher
        .finalize_variable(&mut digest)
        .expect("digest size matches");
    Ok(digest.iter().map(|b| format!("{:02x}", b)).collect())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn write_case(dir: &Path, name: &str, data: &[u8]) -> std::path::PathBuf {
        let p = dir.join(name);
        std::fs::write(&p, data).unwrap();
        p
    }

    fn pattern_200k() -> Vec<u8> {
        b"\xabQZx7".repeat(41000)[..200 * 1024].to_vec()
    }

    // Parity fixtures: digests generated by the original Python
    // implementation (tagdex fingerprint_file, 2026-07-20). These pin the
    // wire format; any change here breaks existing stores.
    #[test]
    fn parity_with_python_implementation() {
        let tmp = tempfile::tempdir().unwrap();
        let cases: &[(&str, Vec<u8>, &str)] = &[
            ("empty.bin", vec![], "c804ce198ec337e3dc762bdd1a09aece"),
            (
                "hello.bin",
                b"hello world".to_vec(),
                "67279e3d124274782e66b2f4d3d079a5",
            ),
            // exactly 2*CHUNK_SIZE: whole-file path boundary
            (
                "exact-128k.bin",
                (0u8..=255).cycle().take(131072).collect(),
                "d27ae5f600820bb3c7a1d6c3b77959a1",
            ),
            // > 2*CHUNK_SIZE: head+tail path
            (
                "large-200k.bin",
                pattern_200k(),
                "b3e89dbcfcd186a2709fea950342a317",
            ),
        ];
        for (name, data, expected) in cases {
            let p = write_case(tmp.path(), name, data);
            assert_eq!(&fingerprint_file(&p).unwrap(), expected, "case {}", name);
        }
    }

    #[test]
    fn middle_change_keeps_fingerprint_head_change_alters_it() {
        // Documents the deliberate head/tail tradeoff, with the collision
        // digest also pinned against the Python implementation.
        let tmp = tempfile::tempdir().unwrap();
        let mut data = pattern_200k();
        data[CHUNK_SIZE as usize + 999] ^= 0xFF;
        let middle = write_case(tmp.path(), "middle.bin", &data);
        assert_eq!(
            fingerprint_file(&middle).unwrap(),
            "b3e89dbcfcd186a2709fea950342a317" // same as unmodified large-200k
        );

        let mut data = pattern_200k();
        data[0] ^= 0xFF;
        let head = write_case(tmp.path(), "head.bin", &data);
        assert_ne!(
            fingerprint_file(&head).unwrap(),
            "b3e89dbcfcd186a2709fea950342a317"
        );
    }

    #[test]
    fn size_is_part_of_fingerprint() {
        let tmp = tempfile::tempdir().unwrap();
        let a = write_case(tmp.path(), "a.bin", &[b'x'; 10]);
        let b = write_case(tmp.path(), "b.bin", &[b'x'; 11]);
        assert_ne!(fingerprint_file(&a).unwrap(), fingerprint_file(&b).unwrap());
    }

    #[test]
    fn missing_file_errors() {
        assert!(fingerprint_file(Path::new("/nonexistent/x")).is_err());
    }
}
